### ISSUE TITLE
Is there any PFF convolution code implemented with CUDA?

### ISSUE THREAD

**Issue by Seokjoongg** [fxmeng/Pruning-Filter-in-Filter#1]
In PFF, I know you suggested PFF Convolution because of the inefficiency of standard convolution. Is there any concrete comparison between the two and any implementation of PFF Convolution in CUDA?

**Comment by fxmeng** [comment]
We haven't finished the CUDA version code, but we give two methods for every to finish it by themself.[https://github.com/fxmeng/Pruning-Filter-in-Filter/blob/master/models/readme.md](url)

**Comment by Seokjoongg** [comment]
thanks i got it!
