### ISSUE TITLE
模型文件

### ISSUE THREAD

**Issue by lgzz** [fxmeng/Pruning-Filter-in-Filter#10]
您的工作非常厉害！能否分享一下您的最终模型文件(VGG16,ResNet56 on CIFAR, 和两个ResNet18 on ImageNet)，想学习研究一下其中的规律。感谢！

**Comment by lgzz** [comment]
自己训练显存不够，非常希望得到您的训练模型结果。

**Comment by fxmeng** [comment]
谢谢关注，
我之前跑的模型没有保存，我给你重新跑了一个模型，尽快保存一下吧，省的链接失效。
链接：https://pan.baidu.com/s/1TTthsrATS9KBjoITcyve9A 
提取码：foj6 
祝好

**Comment by lgzz** [comment]
谢谢
