### ISSUE TITLE
Why did you report results with different settings in the same row?

### ISSUE THREAD

**Issue by stdacore** [fxmeng/Pruning-Filter-in-Filter#11]
The ResNet56 baseline on CIFAR10 has 125M FLOPs and 0.85M params.
The result in table 2 that achieves 77.7% params reduction is the result when alpha=10^-5, delta=0.05 in table 4; however, the result that achieves 75.6% FLOPs reduction is the result when alpha=10^-5, delta=0.09. It's kind of weird.
Please let me know if I have any misunderstanding. Thank you.

**Comment by fxmeng** [comment]
Thank you for your question,
In this paper, we regard a multiply-add operation as 2 flops, so it should have 252.56M flops.
In this way, there should be a 77.7% flops drop and 75.6% parameters drop. It's my mistake to write them in the wrong columns and I will correct them.
thanks for your correction again,
best Regards.

**Comment by stdacore** [comment]
Got it. I think it would be more clear if you add the baseline in Table 4. 
Table 5 seems to have the same issue so it should also be updated.
Anyway, thank you for your reply. You did a good job.
