### ISSUE TITLE
which software did you use to draw the figure 2 in this paper

### ISSUE THREAD

**Issue by yuxiazff** [fxmeng/Pruning-Filter-in-Filter#12]
I have read your paper ‘PRUNING FILTER IN FILTER’, and i find the figure 2 in this paper is very beautiful. Could you please tell me which software you use to draw the figure, thanks!

**Comment by fxmeng** [comment]
Thank you for your commend,
It was drawn by PowerPoint, and the source files are available in this project.

**Comment by fxmeng** [comment]
Wish this will help your work!

**Comment by yuxiazff** [comment]
yes，your work help me a lot. I have run this project successfully. Have a nice day!
