### ISSUE TITLE
关于 multiply the filters’ weights with FS 疑问

### ISSUE THREAD

**Issue by maxiaotian520** [fxmeng/Pruning-Filter-in-Filter#13]
你好，我看到你论文里有写"During training, We multiply the filters’ weights with FS", 但是在code里我看到这一步的实现是在_break 函数中, 我理解的是，这一步不是应该在FS的 update时求loss么？如果放在剪枝里去做，会使weight值在最后骤降。

**Comment by maxiaotian520** [comment]
哦，我看论文后面了，After training, we merge I onto the filter weights W. To further show the importance of the ‘shape’ property, we conduct an experiment where the filters’ weights are fixed, only FS can be optimized during training. 但那为什么最后要执行这一步FS 乘以weight呢？这个跟FS形状似乎没有什么关系。如果你的剪枝时通过改变filter的形状来做的话，那么改变weight的操作完全跟形状无关啊我感觉。

**Comment by fxmeng** [comment]
> 哦，我看论文后面了，After training, we merge I onto the filter weights W. To further show the importance of the ‘shape’ property, we conduct an experiment where the filters’ weights are fixed, only FS can be optimized during training. 但那为什么最后要执行这一步FS 乘以weight呢？这个跟FS形状似乎没有什么关系。如果你的剪枝时通过改变filter的形状来做的话，那么改变weight的操作完全跟形状无关啊我感觉。

FS的每一个值对应着滤波器的一条，
如果FS的值只能为0或1，可以看成hard的形状；
如果FS的值可以为连续值，就可以看成soft的形状。
我们这里稀疏化FS，使大部分值为0，另一部分可以是连续值，算是介于soft和hard之间的一种形状吧。
如果是如果是hard的形状，效果不会太好的（模型量化中，二值网络的效果准确率比较有限）
这篇文章区别量化，讨论的是滤波器的形状对准确率的影响，有点类似更加灵活的inception（最开始这篇文章的idea也是受inception启发的）。

**Comment by maxiaotian520** [comment]
@fxmeng 谢谢回复，还有个问题要请教，就是stripe.py中的prune_in 和 Prune_out, 这两个函数是否是在当有两个连续的convolution时用到的，如果我的convolution是单独出现的，就用不到这两个函数。我是对比你的code在vgg 和 resnet56 里面的用法猜的，不知道是否是这样。

**Comment by fxmeng** [comment]
resnet受限于残差结构，只能裁剪中间的通道，输入输出需要保持一致，所以很难裁剪
