### ISSUE TITLE
resnet56中的update_skeleton为什么只对bn1进行mask更新呢？

### ISSUE THREAD

**Issue by linklist2** [fxmeng/Pruning-Filter-in-Filter#14]
![image](https://user-images.githubusercontent.com/46252413/123725007-e6f37480-d8bf-11eb-96d4-1b5d1906e6eb.png)
您好，我想问的是为何只有残差块中的第一个BN层进行了mask更新呢？

**Comment by fxmeng** [comment]
因为第二个bn层通道如果减少了，就不能和输入的featuremap相加了。

**Comment by linklist2** [comment]
我明白了，谢谢您

**Comment by linklist2** [comment]
> 因为第二个bn层通道如果减少了，就不能和输入的featuremap相加了。

我明白了，谢谢您
