### ISSUE TITLE
为什么有时候没有剪枝效果？

### ISSUE THREAD

**Issue by topsail520** [fxmeng/Pruning-Filter-in-Filter#19]
我的 sr=1e-3，threshold=0.5 ，都没有剪枝效果。sr=1e-2的时候，提示有个维度被置零。

**Comment by fxmeng** [comment]
阈值设置的太大了。sr和threshold开始都不要设置的太大，不然模型效果会迅速变差，参数会大量的被剪掉，然后就无法继续裁剪了。由于参数太少，最终效果也会很差。

**Comment by topsail520** [comment]
非常感谢您百忙之中的解答，谢谢！祝身体健康！
