### ISSUE TITLE
Did the strips really deleted or simply set them to zeros?

### ISSUE THREAD

**Issue by Gaondong** [fxmeng/Pruning-Filter-in-Filter#2]
Thanks for your works！ But how to prune by strips of a `(C*K*K)` kernel ?

**Comment by fxmeng** [comment]
We first set them to zero while training, after that, we pruned all zero stripes, and re-implied the model by stripe-wise convolution layer. (https://github.com/fxmeng/Pruning-Filter-in-Filter/blob/3207012c7e2c159ca51f3a43e4cd9d609f31cd21/models/stripe.py#L47)

**Comment by Gaondong** [comment]
> We first set them to zero while training, after that, we pruned all zero stripes, and re-implied the model by stripe-wise convolution layer. (
> 
> https://github.com/fxmeng/Pruning-Filter-in-Filter/blob/3207012c7e2c159ca51f3a43e4cd9d609f31cd21/models/stripe.py#L47
> 
> )
I saw the stripe-wise in your paper.
Did the final weights could frozen to .pb format for deploy? The kernel weights which shapes is `H*W*Cin*Cout`, could not be saved.

**Comment by fxmeng** [comment]
We change filters from N*C*K*K to (N*K*K)*C*1*1, and can prune each one of the N*K*K stripes.
However, accelerated deployment with CUDA doesn't provide.
You have to complete it by yourself under models/readme.md's instruction.
