### ISSUE TITLE
关于论文中的第六节，SWP持续修剪

### ISSUE THREAD

**Issue by biuado** [fxmeng/Pruning-Filter-in-Filter#20]
作者您好，看了您的论文我觉得您的想法很好，根据您的代码复现了论文结果也不错，但是我比较迷惑的是您论文中说到SWP可以继续对其他方法剪枝的网络进行剪枝，而精度不会明显下降。那么我的疑问是怎么用SWP去修剪用其他剪枝方法修建后的网络，希望您可以给我指点一下，谢谢作者。

**Comment by topsail520** [comment]
同学你好，不知道你有没有在Imagenet数据集上用过这个方法，我尝试用VGG在imagenet数据集上使用，他自定义的Linear会报错，我看到有的同学在resnet18上跑的，线性层使用的却是nn.Linear，不知道是不是他自定义的Linear不能用于224x224的输入

**Comment by topsail520** [comment]
同学你好，不知道你有没有在Imagenet数据集上用过这个方法，我尝试用VGG在imagenet数据集上使用，他自定义的Linear会报错，我看到有的同学在resnet18上跑的，线性层使用的却是nn.Linear，不知道是不是他自定义的Linear不能用于224x224的输入，谢谢！

**Comment by biuado** [comment]
> 

抱歉，我暂时还有没在imagenet上面跑，imagenent太大了，

**Comment by fxmeng** [comment]
> 作者您好，看了您的论文我觉得您的想法很好，根据您的代码复现了论文结果也不错，但是我比较迷惑的是您论文中说到SWP可以继续对其他方法剪枝的网络进行剪枝，而精度不会明显下降。那么我的疑问是怎么用SWP去修剪用其他剪枝方法修建后的网络，希望您可以给我指点一下，谢谢作者。

Filter pruning裁剪后的模型结构仅仅只是改变了卷积的通道数量。可以将SWP的初始通道数改变一下，load其他剪枝方法得到的预训练模型，然后继续进行剪枝。

**Comment by fxmeng** [comment]
> 同学你好，不知道你有没有在Imagenet数据集上用过这个方法，我尝试用VGG在imagenet数据集上使用，他自定义的Linear会报错，我看到有的同学在resnet18上跑的，线性层使用的却是nn.Linear，不知道是不是他自定义的Linear不能用于224x224的输入

他报错应该是ImageNet是224*224的，简单的把这个模型套上去是不行的。可以用pytorch自带的resnet，然后把卷积层用我自定义的FilterStripe替换就可以了。
