### ISSUE TITLE
How to understand the l1norm of paper？

### ISSUE THREAD

**Issue by ShiMinghao0208** [fxmeng/Pruning-Filter-in-Filter#3]
About matrix，the l1 norm is caculate the  max column norm.  So do we think of FS as a matrix? How to understand the l1 norm here? And the l2norm , is it useful？

**Comment by ShiMinghao0208** [comment]
And，How to deal with these errors
![QQ图片20201208203929](https://user-images.githubusercontent.com/53176521/101485191-c56b8380-3995-11eb-9b5a-156d7eaafbc5.png)
![QQ图片20201208203952](https://user-images.githubusercontent.com/53176521/101485250-db794400-3995-11eb-8b29-78ba53aadd9c.png)

**Comment by fxmeng** [comment]
感谢关注，
简单来说，我们使用FS来学习滤波器形状，使用l1norm来稀疏化FS，当FS为零，对应的一条参数就可以被裁剪掉了。
所以l1norm是范数惩罚，你可以用任何惩罚函数来稀疏化FS。

**Comment by fxmeng** [comment]
另外关于你的报错，我是在Linux上跑的，建议换个环境试试

**Comment by ShiMinghao0208** [comment]
好的，十分感谢。另外有个问题是文中出现的l1范数 g(I)对应代码的哪里呢？我大致看了一遍代码有点对应不上

**Comment by ShiMinghao0208** [comment]
> 感谢关注，
> 简单来说，我们使用FS来学习滤波器形状，使用l1norm来稀疏化FS，当FS为零，对应的一条参数就可以被裁剪掉了。
> 所以l1norm是范数惩罚，你可以用任何惩罚函数来稀疏化FS。

还有一个问题是对于文中g(I)的计算表达式下标h，w是笔误吗，因为前面求和的索引是i，j

**Comment by CanQixiaoLan** [comment]
请问sr和threshold这两个参数以什么依据设置合适呢

**Comment by fxmeng** [comment]
> 好的，十分感谢。另外有个问题是文中出现的l1范数 g(I)对应代码的哪里呢？我大致看了一遍代码有点对应不上

https://github.com/fxmeng/Pruning-Filter-in-Filter/blob/a41cdcf772a359ed00b1fe21a07adc1628e46c4e/models/stripe.py#L58

**Comment by fxmeng** [comment]
> > 感谢关注，
> > 简单来说，我们使用FS来学习滤波器形状，使用l1norm来稀疏化FS，当FS为零，对应的一条参数就可以被裁剪掉了。
> > 所以l1norm是范数惩罚，你可以用任何惩罚函数来稀疏化FS。
> 
> 还有一个问题是对于文中g(I)的计算表达式下标h，w是笔误吗，因为前面求和的索引是i，j

不是笔误，论文没必要和代码变量名称保持一致。

**Comment by fxmeng** [comment]
> 请问sr和threshold这两个参数以什么依据设置合适呢

这两个是调出来的超参数。sr决定l1范数惩罚的大小，threshold决定多大l1norm的stripe需要被裁减掉。

**Comment by ShiMinghao0208** [comment]
> > 好的，十分感谢。另外有个问题是文中出现的l1范数 g(I)对应代码的哪里呢？我大致看了一遍代码有点对应不上
> 
> https://github.com/fxmeng/Pruning-Filter-in-Filter/blob/a41cdcf772a359ed00b1fe21a07adc1628e46c4e/models/stripe.py#L58

奥奥，这里是直接计算更新所以不需要再在loss上加上g(I)了是吧。。

另外我指的文中笔误好像跟代码没关系啊...我是指文章前面都是i，j包括求和的符号也是
![QQ图片20201209152408](https://user-images.githubusercontent.com/53176521/101598222-cdc5cc00-3a32-11eb-9918-a2d08c7c3c0f.png)
![QQ图片20201209152431](https://user-images.githubusercontent.com/53176521/101598228-d0282600-3a32-11eb-9c42-7193b4501f83.png)
不知是我理解还是有什么问题吗
多多打扰，不好意思

**Comment by fxmeng** [comment]
> > > 好的，十分感谢。另外有个问题是文中出现的l1范数 g(I)对应代码的哪里呢？我大致看了一遍代码有点对应不上
> > 
> > 
> > https://github.com/fxmeng/Pruning-Filter-in-Filter/blob/a41cdcf772a359ed00b1fe21a07adc1628e46c4e/models/stripe.py#L58
> 
> 奥奥，这里是直接计算更新所以不需要再在loss上加上g(I)了是吧。。
> 
> 另外我指的文中笔误好像跟代码没关系啊...我是指文章前面都是i，j包括求和的符号也是
> ![QQ图片20201209152408](https://user-images.githubusercontent.com/53176521/101598222-cdc5cc00-3a32-11eb-9918-a2d08c7c3c0f.png)
> ![QQ图片20201209152431](https://user-images.githubusercontent.com/53176521/101598228-d0282600-3a32-11eb-9c42-7193b4501f83.png)
> 不知是我理解还是有什么问题吗
> 多多打扰，不好意思

这个也不是笔误，参数W里面全部用的是ij，特征图X里面用的都是hw，代表了不同的含义

**Comment by fxmeng** [comment]
> > > > 好的，十分感谢。另外有个问题是文中出现的l1范数 g(I)对应代码的哪里呢？我大致看了一遍代码有点对应不上
> > > 
> > > 
> > > https://github.com/fxmeng/Pruning-Filter-in-Filter/blob/a41cdcf772a359ed00b1fe21a07adc1628e46c4e/models/stripe.py#L58
> > 
> > 
> > 奥奥，这里是直接计算更新所以不需要再在loss上加上g(I)了是吧。。
> > 另外我指的文中笔误好像跟代码没关系啊...我是指文章前面都是i，j包括求和的符号也是
> > ![QQ图片20201209152408](https://user-images.githubusercontent.com/53176521/101598222-cdc5cc00-3a32-11eb-9918-a2d08c7c3c0f.png)
> > ![QQ图片20201209152431](https://user-images.githubusercontent.com/53176521/101598228-d0282600-3a32-11eb-9c42-7193b4501f83.png)
> > 不知是我理解还是有什么问题吗
> > 多多打扰，不好意思

这个好像还真的笔误了，参数W和I需要使用ij，特征图X需要使用hw

**Comment by fxmeng** [comment]
> > > 好的，十分感谢。另外有个问题是文中出现的l1范数 g(I)对应代码的哪里呢？我大致看了一遍代码有点对应不上
> > 
> > 
> > https://github.com/fxmeng/Pruning-Filter-in-Filter/blob/a41cdcf772a359ed00b1fe21a07adc1628e46c4e/models/stripe.py#L58
> 
> 奥奥，这里是直接计算更新所以不需要再在loss上加上g(I)了是吧。。
> 
> 另外我指的文中笔误好像跟代码没关系啊...我是指文章前面都是i，j包括求和的符号也是
> ![QQ图片20201209152408](https://user-images.githubusercontent.com/53176521/101598222-cdc5cc00-3a32-11eb-9918-a2d08c7c3c0f.png)
> ![QQ图片20201209152431](https://user-images.githubusercontent.com/53176521/101598228-d0282600-3a32-11eb-9c42-7193b4501f83.png)
> 不知是我理解还是有什么问题吗
> 多多打扰，不好意思

这个好像还真的笔误了，参数W和I需要使用ij，特征图X需要使用hw，感谢指正

**Comment by ShiMinghao0208** [comment]
> > > > 好的，十分感谢。另外有个问题是文中出现的l1范数 g(I)对应代码的哪里呢？我大致看了一遍代码有点对应不上
> > > 
> > > 
> > > https://github.com/fxmeng/Pruning-Filter-in-Filter/blob/a41cdcf772a359ed00b1fe21a07adc1628e46c4e/models/stripe.py#L58
> > 
> > 
> > 奥奥，这里是直接计算更新所以不需要再在loss上加上g(I)了是吧。。
> > 另外我指的文中笔误好像跟代码没关系啊...我是指文章前面都是i，j包括求和的符号也是
> > ![QQ图片20201209152408](https://user-images.githubusercontent.com/53176521/101598222-cdc5cc00-3a32-11eb-9918-a2d08c7c3c0f.png)
> > ![QQ图片20201209152431](https://user-images.githubusercontent.com/53176521/101598228-d0282600-3a32-11eb-9c42-7193b4501f83.png)
> > 不知是我理解还是有什么问题吗
> > 多多打扰，不好意思
> 
> 这个好像还真的笔误了，参数W和I需要使用ij，特征图X需要使用hw，感谢指正

奥奥，因为导师对您的这篇文章十分感兴趣，所以叫我务必研究清楚，所以有疑惑的地方就提出来了，也十分感谢您的回答

**Comment by fxmeng** [comment]
> > > > > 好的，十分感谢。另外有个问题是文中出现的l1范数 g(I)对应代码的哪里呢？我大致看了一遍代码有点对应不上
> > > > 
> > > > 
> > > > https://github.com/fxmeng/Pruning-Filter-in-Filter/blob/a41cdcf772a359ed00b1fe21a07adc1628e46c4e/models/stripe.py#L58
> > > 
> > > 
> > > 奥奥，这里是直接计算更新所以不需要再在loss上加上g(I)了是吧。。
> > > 另外我指的文中笔误好像跟代码没关系啊...我是指文章前面都是i，j包括求和的符号也是
> > > ![QQ图片20201209152408](https://user-images.githubusercontent.com/53176521/101598222-cdc5cc00-3a32-11eb-9918-a2d08c7c3c0f.png)
> > > ![QQ图片20201209152431](https://user-images.githubusercontent.com/53176521/101598228-d0282600-3a32-11eb-9c42-7193b4501f83.png)
> > > 不知是我理解还是有什么问题吗
> > > 多多打扰，不好意思
> > 
> > 
> > 这个好像还真的笔误了，参数W和I需要使用ij，特征图X需要使用hw，感谢指正
> 
> 奥奥，因为导师对您的这篇文章十分感兴趣，所以叫我务必研究清楚，所以有疑惑的地方就提出来了，也十分感谢您的回答

感谢关注

**Comment by CanQixiaoLan** [comment]
> > 请问sr和threshold这两个参数以什么依据设置合适呢
> 
> 这两个是调出来的超参数。sr决定l1范数惩罚的大小，threshold决定多大l1norm的stripe需要被裁减掉。

谢谢~

**Comment by 09876qwert** [comment]
self.FilterSkeleton.grad.data.add_(sr * torch.sign(self.FilterSkeleton.data)) 
你好，上段代码里，我看是直接把loss加到原有梯度上了，不应该加的是梯度吗？

**Comment by gaoxuzhang223** [comment]
> 感谢关注，
> 简单来说，我们使用FS来学习滤波器形状，使用l1norm来稀疏化FS，当FS为零，对应的一条参数就可以被裁剪掉了。
> 所以l1norm是范数惩罚，你可以用任何惩罚函数来稀疏化FS。

 老师您好，最近有幸在研究您的这篇论文，在应用到自己的数据集上的时候，模型有不错的表现，但是剪枝的结果却很糟糕，指标和剪枝比例没有明显的规律，不知道问题在哪里，在参数的确定和调节方面，或者其他可能影响的因素，您能给一些建议吗？

**Comment by fxmeng** [comment]
> > 感谢关注，
> > 简单来说，我们使用FS来学习滤波器形状，使用l1norm来稀疏化FS，当FS为零，对应的一条参数就可以被裁剪掉了。
> > 所以l1norm是范数惩罚，你可以用任何惩罚函数来稀疏化FS。
> 
> 老师您好，最近有幸在研究您的这篇论文，在应用到自己的数据集上的时候，模型有不错的表现，但是剪枝的结果却很糟糕，指标和剪枝比例没有明显的规律，不知道问题在哪里，在参数的确定和调节方面，或者其他可能影响的因素，您能给一些建议吗？

您的任务是什么呢？数据集规模大概有多大？可否提供更多信息
看您的描述不做剪枝模型是能够满足条件的，但是剪枝时候效果会下降，还是剪枝的比例比较低呢？
文章里使用l1norm来稀疏化FS，当稀疏化稀疏很小时，效果应该不变，压缩率也低。
正常来说逐渐增大这个比例，压缩率会增大，准确率应该先略微升高或不变（由于模型存在冗余），再逐渐降低。
建议多次重复实验，看看是否是一些随机的情况。
基于稀疏化的剪枝一般会有这种现象，但是由于loss不是朝着最佳优化方向走了，对于一些数据分布不那么好的模型，可能会影响效果。如果是这一点，可以结合一些数据增广的方案，让训练更稳定。
如果一直效果不好，可以考虑不用l1norm惩罚FS，结合一些其他文章的评价标准来进行one shot剪枝。

**Comment by gaoxuzhang223** [comment]
老师您好。很感谢你的回答，很荣幸与您这样交流。我是想在(N，1, 2, 128)这样的输入数据形式上做11分类任务，数据量大约在20万左右, 目前的测试模型是Resnet56 ,考虑到未剪枝模型的分类效果没有问题，就在剪枝上做了多组调节参数的实验，最终出现一个糟糕的情况：剪掉很小很小的比例，模型精度就大幅下降；另外将原数据集转换为图像数据集，有着很高的压缩比例，但是几乎没有精度上的损失，很惊叹老师的这种方法；谢谢老师！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fxmeng/Pruning-Filter-in-Filter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月16日(星期五) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fxmeng/Pruning-Filter-in-Filter] How to understand the l1norm of paper？ (#3)





   
感谢关注，
 简单来说，我们使用FS来学习滤波器形状，使用l1norm来稀疏化FS，当FS为零，对应的一条参数就可以被裁剪掉了。
 所以l1norm是范数惩罚，你可以用任何惩罚函数来稀疏化FS。
  
老师您好，最近有幸在研究您的这篇论文，在应用到自己的数据集上的时候，模型有不错的表现，但是剪枝的结果却很糟糕，指标和剪枝比例没有明显的规律，不知道问题在哪里，在参数的确定和调节方面，或者其他可能影响的因素，您能给一些建议吗？
  
您的任务是什么呢？数据集规模大概有多大？可否提供更多信息
 看您的描述不做剪枝模型是能够满足条件的，但是剪枝时候效果会下降，还是剪枝的比例比较低呢？
 文章里使用l1norm来稀疏化FS，当稀疏化稀疏很小时，效果应该不变，压缩率也低。
 正常来说逐渐增大这个比例，压缩率会增大，准确率应该先略微升高或不变（由于模型存在冗余），再逐渐降低。
 建议多次重复实验，看看是否是一些随机的情况。
 基于稀疏化的剪枝一般会有这种现象，但是由于loss不是朝着最佳优化方向走了，对于一些数据分布不那么好的模型，可能会影响效果。如果是这一点，可以结合一些数据增广的方案，让训练更稳定。
 如果一直效果不好，可以考虑不用l1norm惩罚FS，结合一些其他文章的评价标准来进行one shot剪枝。

**Comment by fxmeng** [comment]
> 老师您好。很感谢你的回答，很荣幸与您这样交流。我是想在(N，1, 2, 128)这样的输入数据形式上做11分类任务，数据量大约在20万左右, 目前的测试模型是Resnet56 ,考虑到未剪枝模型的分类效果没有问题，就在剪枝上做了多组调节参数的实验，最终出现一个糟糕的情况：剪掉很小很小的比例，模型精度就大幅下降；另外将原数据集转换为图像数据集，有着很高的压缩比例，但是几乎没有精度上的损失，很惊叹老师的这种方法；谢谢老师！
> […](#)

谢谢夸奖，我其实不是什么老师，一个研究生学长而已。
N，1, 2, 128这样的数据是不是不适合用2d卷积了，可以考虑1d卷积，初始感受野大一些，然后用这种方法裁剪，可能会有更进一步的效果。

**Comment by gaoxuzhang223** [comment]
收到收到。谢谢学长，我再研究研究。祝学长学业顺利，蒸蒸日上。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fxmeng/Pruning-Filter-in-Filter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月16日(星期五) 下午3:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fxmeng/Pruning-Filter-in-Filter] How to understand the l1norm of paper？ (#3)





  
老师您好。很感谢你的回答，很荣幸与您这样交流。我是想在(N，1, 2, 128)这样的输入数据形式上做11分类任务，数据量大约在20万左右, 目前的测试模型是Resnet56 ,考虑到未剪枝模型的分类效果没有问题，就在剪枝上做了多组调节参数的实验，最终出现一个糟糕的情况：剪掉很小很小的比例，模型精度就大幅下降；另外将原数据集转换为图像数据集，有着很高的压缩比例，但是几乎没有精度上的损失，很惊叹老师的这种方法；谢谢老师！
 …
  
谢谢夸奖，我其实不是什么老师，一个研究生学长而已。
 N，1, 2, 128这样的数据是不是不适合用2d卷积了，可以考虑1d卷积，初始感受野大一些，然后用这种方法裁剪，可能会有更进一步的效果。

**Comment by guohao02** [comment]
> 感谢关注，
> 简单来说，我们使用FS来学习滤波器形状，使用l1norm来稀疏化FS，当FS为零，对应的一条参数就可以被裁剪掉了。
> 所以l1norm是范数惩罚，你可以用任何惩罚函数来稀疏化FS。



> 感谢关注，
> 简单来说，我们使用FS来学习滤波器形状，使用l1norm来稀疏化FS，当FS为零，对应的一条参数就可以被裁剪掉了。
> 所以l1norm是范数惩罚，你可以用任何惩罚函数来稀疏化FS。

![image](https://user-images.githubusercontent.com/80331072/115491744-1b7cfb80-a293-11eb-8e1a-dc5188ae4a36.png)
请问这句段代码什么意思啊？

**Comment by fxmeng** [comment]
> > 感谢关注，
> > 简单来说，我们使用FS来学习滤波器形状，使用l1norm来稀疏化FS，当FS为零，对应的一条参数就可以被裁剪掉了。
> > 所以l1norm是范数惩罚，你可以用任何惩罚函数来稀疏化FS。
> 
> > 感谢关注，
> > 简单来说，我们使用FS来学习滤波器形状，使用l1norm来稀疏化FS，当FS为零，对应的一条参数就可以被裁剪掉了。
> > 所以l1norm是范数惩罚，你可以用任何惩罚函数来稀疏化FS。
> 
> ![image](https://user-images.githubusercontent.com/80331072/115491744-1b7cfb80-a293-11eb-8e1a-dc5188ae4a36.png)
> 请问这句段代码什么意思啊？

3*3卷积可以由1*1卷积先相乘再相加来实现，在相加之前需要按照空间位置移位，详细可以参考这篇文章：Shift: A Zero FLOP, Zero Parameter Alternative to Spatial Convolutions

**Comment by guohao02** [comment]
> Shift: A Zero FLOP, Zero Parameter Alternative to Spatial Convolutions

谢谢学长

**Comment by guohao02** [comment]
![image](https://user-images.githubusercontent.com/80331072/115665707-3ffdd400-a376-11eb-8df5-21bb92be7b4d.png)
![image](https://user-images.githubusercontent.com/80331072/115665760-4e4bf000-a376-11eb-9612-e0680c60786e.png)
学长，为什么这两个公式对权重和输入的下标不一样啊？一个是+i、+j，一个是-i、-j，我挺疑惑的

**Comment by fxmeng** [comment]
这两个公式都是对的，但是一个是-1，0，1，一个是1，0，-1。
当时写文章时候，两个公式没有统一好，在后来的arxiv版本进行了修正。
给您造成困扰，抱歉了

**Comment by guohao02** [comment]
> 这两个公式都是对的，但是一个是-1，0，1，一个是1，0，-1。
> 当时写文章时候，两个公式没有统一好，在后来的arxiv版本进行了修正。
> 给您造成困扰，抱歉了

如果都是对的，那两个公式中相同的wij对应相乘的x点是不是不一样啊？那为啥两个公式都是对的啊？
我的理解第二个公式的下标是对的

**Comment by fxmeng** [comment]
> > 这两个公式都是对的，但是一个是-1，0，1，一个是1，0，-1。
> > 当时写文章时候，两个公式没有统一好，在后来的arxiv版本进行了修正。
> > 给您造成困扰，抱歉了
> 
> 如果都是对的，那两个公式中相同的wij对应相乘的x点是不是不一样啊？那为啥两个公式都是对的啊？
> 我的理解第二个公式的下标是对的

你可以把K=3代进公式里，会发现每个最终都是相邻的9个stripe进行相乘相加
