### ISSUE TITLE
Some existing works

### ISSUE THREAD

**Issue by HolmesShuan** [fxmeng/Pruning-Filter-in-Filter#4]
Hi, the idea of pattern sparsity is very interesting. Nice work! I notice that there are some previous approaches that share the same idea. Could you please give a brief discussion on these works? Thanks in advance.

[1] PCONV: The Missing but Desirable Sparsity in DNN Weight Pruning for Real-time Execution on Mobile Devices. 
[2] PatDNN: Achieving Real-Time DNN Execution on Mobile Devices with Pattern-based Weight Pruning.

**Comment by fxmeng** [comment]
Thanks for your interest,
These two papers propose a pattern-based pruning approach and achieve the benefits of both non-structured and structured pruning.
However, they all constraint filters' shape in some certain way. e.g. In PCONV, the filter's shape is selected from a few options, and PatDNN fixes the number of remaining stripes.
In our paper, the filter can be freely pruned into any shape. Each filter's shape only seeks to fit its needs.

**Comment by fxmeng** [comment]
> Hi, the idea of pattern sparsity is very interesting. Nice work! I notice that there are some previous approaches that share the same idea. Could you please give a brief discussion on these works? Thanks in advance.
> 
> [1] PCONV: The Missing but Desirable Sparsity in DNN Weight Pruning for Real-time Execution on Mobile Devices.
> [2] PatDNN: Achieving Real-Time DNN Execution on Mobile Devices with Pattern-based Weight Pruning.

Thanks for your interest,
These two papers propose a pattern-based pruning approach and achieve the benefits of both non-structured and structured pruning.
However, they all constraint filters' shape in some certain way. e.g. In PCONV, the filter's shape is selected from a few options, and PatDNN fixes the number of remaining stripes.
In our paper, the filter can be freely pruned into any shape. Each filter's shape only seeks to fit its needs.

**Comment by HolmesShuan** [comment]
That sounds reasonable. Have you ever tried to implement Pruning-Filter-in-Filter on Mobile devices? I found PatDNN report encouraging real speedups and accuracy improvements over baselines, which makes me wonder whether the free shape pruning still enjoys such benefits. THX.

**Comment by fxmeng** [comment]
> That sounds reasonable. Have you ever tried to implement Pruning-Filter-in-Filter on Mobile devices? I found PatDNN report encouraging real speedups and accuracy improvements over baselines, which makes me wonder whether the free shape pruning still enjoys such benefits. THX.
we are working on it
