### ISSUE TITLE
关于剪枝后的模型尺寸问题

### ISSUE THREAD

**Issue by Lucky-BenXie** [fxmeng/Pruning-Filter-in-Filter#6]
您好，想请问下为什么剪枝后网络结构是这种[576,64,1,1],剪枝后的卷积核都成1x1大小，希望您可以解答下。
![image](https://user-images.githubusercontent.com/58413357/102326314-3bd43b00-3fbf-11eb-84f4-35d0ee8c992f.png)

**Comment by Lucky-BenXie** [comment]
@fxmeng 看了代码大概明白，但是还有一个问题就是：这样裁剪后的网络结构应该如何和模型保持一致呀？我的理解这样裁剪后网络前后的channel维度都不一致了,希望您可以解答下。

**Comment by fxmeng** [comment]
做乘法的时候确实通道数不同了，但最终会把不同位置的输出相加，最终结果是一致的。

**Comment by Lucky-BenXie** [comment]
@fxmeng  谢谢，那我如何搭建裁剪后的网络结构，我打印出来的网络大概这样子，这样的话每层的channel都不一样了，包括比如上一层输出channel是222,下层BN层输入的channel则为64,这让我很疑惑？
![image](https://user-images.githubusercontent.com/58413357/102448323-da6aa580-406c-11eb-94ce-634989ac4d09.png)

**Comment by fxmeng** [comment]
这222维的stripe-wise卷积输出的222个feature map最终会组合为64个通道，进入bn层。本文将原来的卷积计算顺序改变了，先逐条相乘，再逐条相加。建议仔细研究下论文，配合理解代码。

**Comment by Lucky-BenXie** [comment]
> 这222维的stripe-wise卷积输出的222个feature map最终会组合为64个通道，进入bn层。本文将原来的卷积计算顺序改变了，先逐条相乘，再逐条相加。建议仔细研究下论文，配合理解代码。

好的，感觉您的解答。
