### ISSUE TITLE
多卡训练问题

### ISSUE THREAD

**Issue by 09876qwert** [fxmeng/Pruning-Filter-in-Filter#7]
你好，我这边用你的代码裁减我的轻量级检测模型，采用单卡训练时候各项指标是正常的，但切换到多卡时候指标下降的很明显，请问你这种方法不能多卡训练吗，谢谢

**Comment by fxmeng** [comment]
你好，感谢关注，
我在实验中没有使用多卡训练。想确认一下你使用的是哪种多卡训练方法，指标下降是指即使不稀疏化，指标也会下降吗？
如果方便，希望能够提供更多修改的信息。

**Comment by 09876qwert** [comment]
用的是英伟达的V100。是的，即使不稀疏化，指标也会下降。除此之外的话，BN我用的是同步BN。
我还有一个问题，你的这个裁剪的训练应该是从头训练的吧，不能pretrain的训练吧，这种情况下，我这边是这个问题，我用一个已经训练好的一个模型对裁剪模型进行初始化，但这时候模型参数以及训练的很好了，所以FS参数应该不怎么学习了，所以导致模型裁剪效果很不理想

**Comment by 09876qwert** [comment]
我现在的做法是模型裸训，而且等模型迭代几个epoch再裁剪

**Comment by fxmeng** [comment]
嗯嗯，预训练的模型没有任何限制，每个滤波器的不同通道可能学习到的形状不同，所以很难裁剪。
如果在训练时约束相同的形状尽量出现在同一个滤波器里，这样会更有利于裁剪。
不过相信SWP的潜力是有的，祝好。

**Comment by 09876qwert** [comment]
请问有什么办法能实现训练时约束相同的形状尽量出现在同一个滤波器里呢？

**Comment by fxmeng** [comment]
我这里用的是最简单的，通过稀疏化FS来逼他们形状保持一致，其实之前也设计过一个loss来达成这一效果，不过这些方法都是在训练时做的。如果像你提问的，pretrain的模型怎么做，或许将训练好的模型，按照每个输入通道的相似性调整一下滤波器里面的通道，然后再裁剪，retrain，不知道会不会有效。

**Comment by 09876qwert** [comment]
你好，我确认了一下，我用的是单机多卡分布式训练（DistributedDataParallel），这种训练方式能用在模型裁剪吗

**Comment by fxmeng** [comment]
> 你好，我确认了一下，我用的是单机多卡分布式训练（DistributedDataParallel），这种训练方式能用在模型裁剪吗

我没有做过分布训练的实验，不过如果你使用了DistributedDataParallel，我之前设置的batchsize可能就比较小了，也许需要重新调一下。你说的效果多卡效果下降不知道能不能通过调节batchsize解决。
